/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SuccessRouteImport } from './routes/success'
import { Route as SubscriptionRequiredRouteImport } from './routes/subscription-required'
import { Route as SignUpRouteImport } from './routes/sign-up'
import { Route as SignInRouteImport } from './routes/sign-in'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as HealthRouteImport } from './routes/health'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as AddressFinderCartesiaRouteImport } from './routes/address-finder-cartesia'
import { Route as AddressFinderRouteImport } from './routes/address-finder'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ListingsIndexRouteImport } from './routes/listings.index'
import { Route as DashboardIndexRouteImport } from './routes/dashboard.index'
import { Route as BlogIndexRouteImport } from './routes/blog.index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as SignUpSplatRouteImport } from './routes/sign-up.$'
import { Route as SignInSplatRouteImport } from './routes/sign-in.$'
import { Route as ListingsMyListingsRouteImport } from './routes/listings.my-listings'
import { Route as ListingsCreateRouteImport } from './routes/listings.create'
import { Route as ListingsStateRouteImport } from './routes/listings.$state'
import { Route as DashboardSettingsRouteImport } from './routes/dashboard.settings'
import { Route as DashboardChatRouteImport } from './routes/dashboard.chat'
import { Route as BlogSlugRouteImport } from './routes/blog.$slug'
import { Route as AdminListingsIndexRouteImport } from './routes/admin.listings.index'
import { Route as ListingsStateTypeRouteImport } from './routes/listings.$state.$type'
import { Route as ApiAddressValidateRouteImport } from './routes/api.address.validate'
import { Route as ApiAddressSelectRouteImport } from './routes/api.address.select'
import { Route as ApiAddressSearchRouteImport } from './routes/api.address.search'
import { Route as ApiAddressDetailsRouteImport } from './routes/api.address.details'
import { Route as AdminListingsCreateRouteImport } from './routes/admin.listings.create'
import { Route as ListingsStateTypeSuburbRouteImport } from './routes/listings.$state.$type.$suburb'
import { Route as AdminListingsEditIdRouteImport } from './routes/admin.listings.edit.$id'
import { Route as ListingsStateTypeSuburbIdRouteImport } from './routes/listings.$state.$type.$suburb.$id'
import { Route as ListingsStateTypeSuburbIdMatchesRouteImport } from './routes/listings.$state.$type.$suburb.$id.matches'
import { Route as ListingsStateTypeSuburbIdEditRouteImport } from './routes/listings.$state.$type.$suburb.$id.edit'
import { Route as ListingsStateTypeSuburbIdMatchesMatchIdRouteImport } from './routes/listings.$state.$type.$suburb.$id.matches.$matchId'

const SuccessRoute = SuccessRouteImport.update({
  id: '/success',
  path: '/success',
  getParentRoute: () => rootRouteImport,
} as any)
const SubscriptionRequiredRoute = SubscriptionRequiredRouteImport.update({
  id: '/subscription-required',
  path: '/subscription-required',
  getParentRoute: () => rootRouteImport,
} as any)
const SignUpRoute = SignUpRouteImport.update({
  id: '/sign-up',
  path: '/sign-up',
  getParentRoute: () => rootRouteImport,
} as any)
const SignInRoute = SignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const HealthRoute = HealthRouteImport.update({
  id: '/health',
  path: '/health',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AddressFinderCartesiaRoute = AddressFinderCartesiaRouteImport.update({
  id: '/address-finder-cartesia',
  path: '/address-finder-cartesia',
  getParentRoute: () => rootRouteImport,
} as any)
const AddressFinderRoute = AddressFinderRouteImport.update({
  id: '/address-finder',
  path: '/address-finder',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ListingsIndexRoute = ListingsIndexRouteImport.update({
  id: '/listings/',
  path: '/listings/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRoute,
} as any)
const BlogIndexRoute = BlogIndexRouteImport.update({
  id: '/blog/',
  path: '/blog/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => rootRouteImport,
} as any)
const SignUpSplatRoute = SignUpSplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => SignUpRoute,
} as any)
const SignInSplatRoute = SignInSplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => SignInRoute,
} as any)
const ListingsMyListingsRoute = ListingsMyListingsRouteImport.update({
  id: '/listings/my-listings',
  path: '/listings/my-listings',
  getParentRoute: () => rootRouteImport,
} as any)
const ListingsCreateRoute = ListingsCreateRouteImport.update({
  id: '/listings/create',
  path: '/listings/create',
  getParentRoute: () => rootRouteImport,
} as any)
const ListingsStateRoute = ListingsStateRouteImport.update({
  id: '/listings/$state',
  path: '/listings/$state',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardSettingsRoute = DashboardSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardChatRoute = DashboardChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => DashboardRoute,
} as any)
const BlogSlugRoute = BlogSlugRouteImport.update({
  id: '/blog/$slug',
  path: '/blog/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminListingsIndexRoute = AdminListingsIndexRouteImport.update({
  id: '/admin/listings/',
  path: '/admin/listings/',
  getParentRoute: () => rootRouteImport,
} as any)
const ListingsStateTypeRoute = ListingsStateTypeRouteImport.update({
  id: '/$type',
  path: '/$type',
  getParentRoute: () => ListingsStateRoute,
} as any)
const ApiAddressValidateRoute = ApiAddressValidateRouteImport.update({
  id: '/api/address/validate',
  path: '/api/address/validate',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAddressSelectRoute = ApiAddressSelectRouteImport.update({
  id: '/api/address/select',
  path: '/api/address/select',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAddressSearchRoute = ApiAddressSearchRouteImport.update({
  id: '/api/address/search',
  path: '/api/address/search',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAddressDetailsRoute = ApiAddressDetailsRouteImport.update({
  id: '/api/address/details',
  path: '/api/address/details',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminListingsCreateRoute = AdminListingsCreateRouteImport.update({
  id: '/admin/listings/create',
  path: '/admin/listings/create',
  getParentRoute: () => rootRouteImport,
} as any)
const ListingsStateTypeSuburbRoute = ListingsStateTypeSuburbRouteImport.update({
  id: '/$suburb',
  path: '/$suburb',
  getParentRoute: () => ListingsStateTypeRoute,
} as any)
const AdminListingsEditIdRoute = AdminListingsEditIdRouteImport.update({
  id: '/admin/listings/edit/$id',
  path: '/admin/listings/edit/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ListingsStateTypeSuburbIdRoute =
  ListingsStateTypeSuburbIdRouteImport.update({
    id: '/$id',
    path: '/$id',
    getParentRoute: () => ListingsStateTypeSuburbRoute,
  } as any)
const ListingsStateTypeSuburbIdMatchesRoute =
  ListingsStateTypeSuburbIdMatchesRouteImport.update({
    id: '/matches',
    path: '/matches',
    getParentRoute: () => ListingsStateTypeSuburbIdRoute,
  } as any)
const ListingsStateTypeSuburbIdEditRoute =
  ListingsStateTypeSuburbIdEditRouteImport.update({
    id: '/edit',
    path: '/edit',
    getParentRoute: () => ListingsStateTypeSuburbIdRoute,
  } as any)
const ListingsStateTypeSuburbIdMatchesMatchIdRoute =
  ListingsStateTypeSuburbIdMatchesMatchIdRouteImport.update({
    id: '/$matchId',
    path: '/$matchId',
    getParentRoute: () => ListingsStateTypeSuburbIdMatchesRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/address-finder': typeof AddressFinderRoute
  '/address-finder-cartesia': typeof AddressFinderCartesiaRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/health': typeof HealthRoute
  '/pricing': typeof PricingRoute
  '/sign-in': typeof SignInRouteWithChildren
  '/sign-up': typeof SignUpRouteWithChildren
  '/subscription-required': typeof SubscriptionRequiredRoute
  '/success': typeof SuccessRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/dashboard/chat': typeof DashboardChatRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/listings/$state': typeof ListingsStateRouteWithChildren
  '/listings/create': typeof ListingsCreateRoute
  '/listings/my-listings': typeof ListingsMyListingsRoute
  '/sign-in/$': typeof SignInSplatRoute
  '/sign-up/$': typeof SignUpSplatRoute
  '/admin/': typeof AdminIndexRoute
  '/blog/': typeof BlogIndexRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/listings/': typeof ListingsIndexRoute
  '/admin/listings/create': typeof AdminListingsCreateRoute
  '/api/address/details': typeof ApiAddressDetailsRoute
  '/api/address/search': typeof ApiAddressSearchRoute
  '/api/address/select': typeof ApiAddressSelectRoute
  '/api/address/validate': typeof ApiAddressValidateRoute
  '/listings/$state/$type': typeof ListingsStateTypeRouteWithChildren
  '/admin/listings/': typeof AdminListingsIndexRoute
  '/admin/listings/edit/$id': typeof AdminListingsEditIdRoute
  '/listings/$state/$type/$suburb': typeof ListingsStateTypeSuburbRouteWithChildren
  '/listings/$state/$type/$suburb/$id': typeof ListingsStateTypeSuburbIdRouteWithChildren
  '/listings/$state/$type/$suburb/$id/edit': typeof ListingsStateTypeSuburbIdEditRoute
  '/listings/$state/$type/$suburb/$id/matches': typeof ListingsStateTypeSuburbIdMatchesRouteWithChildren
  '/listings/$state/$type/$suburb/$id/matches/$matchId': typeof ListingsStateTypeSuburbIdMatchesMatchIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/address-finder': typeof AddressFinderRoute
  '/address-finder-cartesia': typeof AddressFinderCartesiaRoute
  '/health': typeof HealthRoute
  '/pricing': typeof PricingRoute
  '/sign-in': typeof SignInRouteWithChildren
  '/sign-up': typeof SignUpRouteWithChildren
  '/subscription-required': typeof SubscriptionRequiredRoute
  '/success': typeof SuccessRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/dashboard/chat': typeof DashboardChatRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/listings/$state': typeof ListingsStateRouteWithChildren
  '/listings/create': typeof ListingsCreateRoute
  '/listings/my-listings': typeof ListingsMyListingsRoute
  '/sign-in/$': typeof SignInSplatRoute
  '/sign-up/$': typeof SignUpSplatRoute
  '/admin': typeof AdminIndexRoute
  '/blog': typeof BlogIndexRoute
  '/dashboard': typeof DashboardIndexRoute
  '/listings': typeof ListingsIndexRoute
  '/admin/listings/create': typeof AdminListingsCreateRoute
  '/api/address/details': typeof ApiAddressDetailsRoute
  '/api/address/search': typeof ApiAddressSearchRoute
  '/api/address/select': typeof ApiAddressSelectRoute
  '/api/address/validate': typeof ApiAddressValidateRoute
  '/listings/$state/$type': typeof ListingsStateTypeRouteWithChildren
  '/admin/listings': typeof AdminListingsIndexRoute
  '/admin/listings/edit/$id': typeof AdminListingsEditIdRoute
  '/listings/$state/$type/$suburb': typeof ListingsStateTypeSuburbRouteWithChildren
  '/listings/$state/$type/$suburb/$id': typeof ListingsStateTypeSuburbIdRouteWithChildren
  '/listings/$state/$type/$suburb/$id/edit': typeof ListingsStateTypeSuburbIdEditRoute
  '/listings/$state/$type/$suburb/$id/matches': typeof ListingsStateTypeSuburbIdMatchesRouteWithChildren
  '/listings/$state/$type/$suburb/$id/matches/$matchId': typeof ListingsStateTypeSuburbIdMatchesMatchIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/address-finder': typeof AddressFinderRoute
  '/address-finder-cartesia': typeof AddressFinderCartesiaRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/health': typeof HealthRoute
  '/pricing': typeof PricingRoute
  '/sign-in': typeof SignInRouteWithChildren
  '/sign-up': typeof SignUpRouteWithChildren
  '/subscription-required': typeof SubscriptionRequiredRoute
  '/success': typeof SuccessRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/dashboard/chat': typeof DashboardChatRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/listings/$state': typeof ListingsStateRouteWithChildren
  '/listings/create': typeof ListingsCreateRoute
  '/listings/my-listings': typeof ListingsMyListingsRoute
  '/sign-in/$': typeof SignInSplatRoute
  '/sign-up/$': typeof SignUpSplatRoute
  '/admin/': typeof AdminIndexRoute
  '/blog/': typeof BlogIndexRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/listings/': typeof ListingsIndexRoute
  '/admin/listings/create': typeof AdminListingsCreateRoute
  '/api/address/details': typeof ApiAddressDetailsRoute
  '/api/address/search': typeof ApiAddressSearchRoute
  '/api/address/select': typeof ApiAddressSelectRoute
  '/api/address/validate': typeof ApiAddressValidateRoute
  '/listings/$state/$type': typeof ListingsStateTypeRouteWithChildren
  '/admin/listings/': typeof AdminListingsIndexRoute
  '/admin/listings/edit/$id': typeof AdminListingsEditIdRoute
  '/listings/$state/$type/$suburb': typeof ListingsStateTypeSuburbRouteWithChildren
  '/listings/$state/$type/$suburb/$id': typeof ListingsStateTypeSuburbIdRouteWithChildren
  '/listings/$state/$type/$suburb/$id/edit': typeof ListingsStateTypeSuburbIdEditRoute
  '/listings/$state/$type/$suburb/$id/matches': typeof ListingsStateTypeSuburbIdMatchesRouteWithChildren
  '/listings/$state/$type/$suburb/$id/matches/$matchId': typeof ListingsStateTypeSuburbIdMatchesMatchIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/address-finder'
    | '/address-finder-cartesia'
    | '/dashboard'
    | '/health'
    | '/pricing'
    | '/sign-in'
    | '/sign-up'
    | '/subscription-required'
    | '/success'
    | '/blog/$slug'
    | '/dashboard/chat'
    | '/dashboard/settings'
    | '/listings/$state'
    | '/listings/create'
    | '/listings/my-listings'
    | '/sign-in/$'
    | '/sign-up/$'
    | '/admin/'
    | '/blog/'
    | '/dashboard/'
    | '/listings/'
    | '/admin/listings/create'
    | '/api/address/details'
    | '/api/address/search'
    | '/api/address/select'
    | '/api/address/validate'
    | '/listings/$state/$type'
    | '/admin/listings/'
    | '/admin/listings/edit/$id'
    | '/listings/$state/$type/$suburb'
    | '/listings/$state/$type/$suburb/$id'
    | '/listings/$state/$type/$suburb/$id/edit'
    | '/listings/$state/$type/$suburb/$id/matches'
    | '/listings/$state/$type/$suburb/$id/matches/$matchId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/address-finder'
    | '/address-finder-cartesia'
    | '/health'
    | '/pricing'
    | '/sign-in'
    | '/sign-up'
    | '/subscription-required'
    | '/success'
    | '/blog/$slug'
    | '/dashboard/chat'
    | '/dashboard/settings'
    | '/listings/$state'
    | '/listings/create'
    | '/listings/my-listings'
    | '/sign-in/$'
    | '/sign-up/$'
    | '/admin'
    | '/blog'
    | '/dashboard'
    | '/listings'
    | '/admin/listings/create'
    | '/api/address/details'
    | '/api/address/search'
    | '/api/address/select'
    | '/api/address/validate'
    | '/listings/$state/$type'
    | '/admin/listings'
    | '/admin/listings/edit/$id'
    | '/listings/$state/$type/$suburb'
    | '/listings/$state/$type/$suburb/$id'
    | '/listings/$state/$type/$suburb/$id/edit'
    | '/listings/$state/$type/$suburb/$id/matches'
    | '/listings/$state/$type/$suburb/$id/matches/$matchId'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/address-finder'
    | '/address-finder-cartesia'
    | '/dashboard'
    | '/health'
    | '/pricing'
    | '/sign-in'
    | '/sign-up'
    | '/subscription-required'
    | '/success'
    | '/blog/$slug'
    | '/dashboard/chat'
    | '/dashboard/settings'
    | '/listings/$state'
    | '/listings/create'
    | '/listings/my-listings'
    | '/sign-in/$'
    | '/sign-up/$'
    | '/admin/'
    | '/blog/'
    | '/dashboard/'
    | '/listings/'
    | '/admin/listings/create'
    | '/api/address/details'
    | '/api/address/search'
    | '/api/address/select'
    | '/api/address/validate'
    | '/listings/$state/$type'
    | '/admin/listings/'
    | '/admin/listings/edit/$id'
    | '/listings/$state/$type/$suburb'
    | '/listings/$state/$type/$suburb/$id'
    | '/listings/$state/$type/$suburb/$id/edit'
    | '/listings/$state/$type/$suburb/$id/matches'
    | '/listings/$state/$type/$suburb/$id/matches/$matchId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AddressFinderRoute: typeof AddressFinderRoute
  AddressFinderCartesiaRoute: typeof AddressFinderCartesiaRoute
  DashboardRoute: typeof DashboardRouteWithChildren
  HealthRoute: typeof HealthRoute
  PricingRoute: typeof PricingRoute
  SignInRoute: typeof SignInRouteWithChildren
  SignUpRoute: typeof SignUpRouteWithChildren
  SubscriptionRequiredRoute: typeof SubscriptionRequiredRoute
  SuccessRoute: typeof SuccessRoute
  BlogSlugRoute: typeof BlogSlugRoute
  ListingsStateRoute: typeof ListingsStateRouteWithChildren
  ListingsCreateRoute: typeof ListingsCreateRoute
  ListingsMyListingsRoute: typeof ListingsMyListingsRoute
  AdminIndexRoute: typeof AdminIndexRoute
  BlogIndexRoute: typeof BlogIndexRoute
  ListingsIndexRoute: typeof ListingsIndexRoute
  AdminListingsCreateRoute: typeof AdminListingsCreateRoute
  ApiAddressDetailsRoute: typeof ApiAddressDetailsRoute
  ApiAddressSearchRoute: typeof ApiAddressSearchRoute
  ApiAddressSelectRoute: typeof ApiAddressSelectRoute
  ApiAddressValidateRoute: typeof ApiAddressValidateRoute
  AdminListingsIndexRoute: typeof AdminListingsIndexRoute
  AdminListingsEditIdRoute: typeof AdminListingsEditIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/success': {
      id: '/success'
      path: '/success'
      fullPath: '/success'
      preLoaderRoute: typeof SuccessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/subscription-required': {
      id: '/subscription-required'
      path: '/subscription-required'
      fullPath: '/subscription-required'
      preLoaderRoute: typeof SubscriptionRequiredRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign-up': {
      id: '/sign-up'
      path: '/sign-up'
      fullPath: '/sign-up'
      preLoaderRoute: typeof SignUpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign-in': {
      id: '/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof SignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/health': {
      id: '/health'
      path: '/health'
      fullPath: '/health'
      preLoaderRoute: typeof HealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/address-finder-cartesia': {
      id: '/address-finder-cartesia'
      path: '/address-finder-cartesia'
      fullPath: '/address-finder-cartesia'
      preLoaderRoute: typeof AddressFinderCartesiaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/address-finder': {
      id: '/address-finder'
      path: '/address-finder'
      fullPath: '/address-finder'
      preLoaderRoute: typeof AddressFinderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/listings/': {
      id: '/listings/'
      path: '/listings'
      fullPath: '/listings/'
      preLoaderRoute: typeof ListingsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/blog/': {
      id: '/blog/'
      path: '/blog'
      fullPath: '/blog/'
      preLoaderRoute: typeof BlogIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign-up/$': {
      id: '/sign-up/$'
      path: '/$'
      fullPath: '/sign-up/$'
      preLoaderRoute: typeof SignUpSplatRouteImport
      parentRoute: typeof SignUpRoute
    }
    '/sign-in/$': {
      id: '/sign-in/$'
      path: '/$'
      fullPath: '/sign-in/$'
      preLoaderRoute: typeof SignInSplatRouteImport
      parentRoute: typeof SignInRoute
    }
    '/listings/my-listings': {
      id: '/listings/my-listings'
      path: '/listings/my-listings'
      fullPath: '/listings/my-listings'
      preLoaderRoute: typeof ListingsMyListingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/listings/create': {
      id: '/listings/create'
      path: '/listings/create'
      fullPath: '/listings/create'
      preLoaderRoute: typeof ListingsCreateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/listings/$state': {
      id: '/listings/$state'
      path: '/listings/$state'
      fullPath: '/listings/$state'
      preLoaderRoute: typeof ListingsStateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/settings': {
      id: '/dashboard/settings'
      path: '/settings'
      fullPath: '/dashboard/settings'
      preLoaderRoute: typeof DashboardSettingsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/chat': {
      id: '/dashboard/chat'
      path: '/chat'
      fullPath: '/dashboard/chat'
      preLoaderRoute: typeof DashboardChatRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/blog/$slug': {
      id: '/blog/$slug'
      path: '/blog/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof BlogSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/listings/': {
      id: '/admin/listings/'
      path: '/admin/listings'
      fullPath: '/admin/listings/'
      preLoaderRoute: typeof AdminListingsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/listings/$state/$type': {
      id: '/listings/$state/$type'
      path: '/$type'
      fullPath: '/listings/$state/$type'
      preLoaderRoute: typeof ListingsStateTypeRouteImport
      parentRoute: typeof ListingsStateRoute
    }
    '/api/address/validate': {
      id: '/api/address/validate'
      path: '/api/address/validate'
      fullPath: '/api/address/validate'
      preLoaderRoute: typeof ApiAddressValidateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/address/select': {
      id: '/api/address/select'
      path: '/api/address/select'
      fullPath: '/api/address/select'
      preLoaderRoute: typeof ApiAddressSelectRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/address/search': {
      id: '/api/address/search'
      path: '/api/address/search'
      fullPath: '/api/address/search'
      preLoaderRoute: typeof ApiAddressSearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/address/details': {
      id: '/api/address/details'
      path: '/api/address/details'
      fullPath: '/api/address/details'
      preLoaderRoute: typeof ApiAddressDetailsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/listings/create': {
      id: '/admin/listings/create'
      path: '/admin/listings/create'
      fullPath: '/admin/listings/create'
      preLoaderRoute: typeof AdminListingsCreateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/listings/$state/$type/$suburb': {
      id: '/listings/$state/$type/$suburb'
      path: '/$suburb'
      fullPath: '/listings/$state/$type/$suburb'
      preLoaderRoute: typeof ListingsStateTypeSuburbRouteImport
      parentRoute: typeof ListingsStateTypeRoute
    }
    '/admin/listings/edit/$id': {
      id: '/admin/listings/edit/$id'
      path: '/admin/listings/edit/$id'
      fullPath: '/admin/listings/edit/$id'
      preLoaderRoute: typeof AdminListingsEditIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/listings/$state/$type/$suburb/$id': {
      id: '/listings/$state/$type/$suburb/$id'
      path: '/$id'
      fullPath: '/listings/$state/$type/$suburb/$id'
      preLoaderRoute: typeof ListingsStateTypeSuburbIdRouteImport
      parentRoute: typeof ListingsStateTypeSuburbRoute
    }
    '/listings/$state/$type/$suburb/$id/matches': {
      id: '/listings/$state/$type/$suburb/$id/matches'
      path: '/matches'
      fullPath: '/listings/$state/$type/$suburb/$id/matches'
      preLoaderRoute: typeof ListingsStateTypeSuburbIdMatchesRouteImport
      parentRoute: typeof ListingsStateTypeSuburbIdRoute
    }
    '/listings/$state/$type/$suburb/$id/edit': {
      id: '/listings/$state/$type/$suburb/$id/edit'
      path: '/edit'
      fullPath: '/listings/$state/$type/$suburb/$id/edit'
      preLoaderRoute: typeof ListingsStateTypeSuburbIdEditRouteImport
      parentRoute: typeof ListingsStateTypeSuburbIdRoute
    }
    '/listings/$state/$type/$suburb/$id/matches/$matchId': {
      id: '/listings/$state/$type/$suburb/$id/matches/$matchId'
      path: '/$matchId'
      fullPath: '/listings/$state/$type/$suburb/$id/matches/$matchId'
      preLoaderRoute: typeof ListingsStateTypeSuburbIdMatchesMatchIdRouteImport
      parentRoute: typeof ListingsStateTypeSuburbIdMatchesRoute
    }
  }
}

interface DashboardRouteChildren {
  DashboardChatRoute: typeof DashboardChatRoute
  DashboardSettingsRoute: typeof DashboardSettingsRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardChatRoute: DashboardChatRoute,
  DashboardSettingsRoute: DashboardSettingsRoute,
  DashboardIndexRoute: DashboardIndexRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

interface SignInRouteChildren {
  SignInSplatRoute: typeof SignInSplatRoute
}

const SignInRouteChildren: SignInRouteChildren = {
  SignInSplatRoute: SignInSplatRoute,
}

const SignInRouteWithChildren =
  SignInRoute._addFileChildren(SignInRouteChildren)

interface SignUpRouteChildren {
  SignUpSplatRoute: typeof SignUpSplatRoute
}

const SignUpRouteChildren: SignUpRouteChildren = {
  SignUpSplatRoute: SignUpSplatRoute,
}

const SignUpRouteWithChildren =
  SignUpRoute._addFileChildren(SignUpRouteChildren)

interface ListingsStateTypeSuburbIdMatchesRouteChildren {
  ListingsStateTypeSuburbIdMatchesMatchIdRoute: typeof ListingsStateTypeSuburbIdMatchesMatchIdRoute
}

const ListingsStateTypeSuburbIdMatchesRouteChildren: ListingsStateTypeSuburbIdMatchesRouteChildren =
  {
    ListingsStateTypeSuburbIdMatchesMatchIdRoute:
      ListingsStateTypeSuburbIdMatchesMatchIdRoute,
  }

const ListingsStateTypeSuburbIdMatchesRouteWithChildren =
  ListingsStateTypeSuburbIdMatchesRoute._addFileChildren(
    ListingsStateTypeSuburbIdMatchesRouteChildren,
  )

interface ListingsStateTypeSuburbIdRouteChildren {
  ListingsStateTypeSuburbIdEditRoute: typeof ListingsStateTypeSuburbIdEditRoute
  ListingsStateTypeSuburbIdMatchesRoute: typeof ListingsStateTypeSuburbIdMatchesRouteWithChildren
}

const ListingsStateTypeSuburbIdRouteChildren: ListingsStateTypeSuburbIdRouteChildren =
  {
    ListingsStateTypeSuburbIdEditRoute: ListingsStateTypeSuburbIdEditRoute,
    ListingsStateTypeSuburbIdMatchesRoute:
      ListingsStateTypeSuburbIdMatchesRouteWithChildren,
  }

const ListingsStateTypeSuburbIdRouteWithChildren =
  ListingsStateTypeSuburbIdRoute._addFileChildren(
    ListingsStateTypeSuburbIdRouteChildren,
  )

interface ListingsStateTypeSuburbRouteChildren {
  ListingsStateTypeSuburbIdRoute: typeof ListingsStateTypeSuburbIdRouteWithChildren
}

const ListingsStateTypeSuburbRouteChildren: ListingsStateTypeSuburbRouteChildren =
  {
    ListingsStateTypeSuburbIdRoute: ListingsStateTypeSuburbIdRouteWithChildren,
  }

const ListingsStateTypeSuburbRouteWithChildren =
  ListingsStateTypeSuburbRoute._addFileChildren(
    ListingsStateTypeSuburbRouteChildren,
  )

interface ListingsStateTypeRouteChildren {
  ListingsStateTypeSuburbRoute: typeof ListingsStateTypeSuburbRouteWithChildren
}

const ListingsStateTypeRouteChildren: ListingsStateTypeRouteChildren = {
  ListingsStateTypeSuburbRoute: ListingsStateTypeSuburbRouteWithChildren,
}

const ListingsStateTypeRouteWithChildren =
  ListingsStateTypeRoute._addFileChildren(ListingsStateTypeRouteChildren)

interface ListingsStateRouteChildren {
  ListingsStateTypeRoute: typeof ListingsStateTypeRouteWithChildren
}

const ListingsStateRouteChildren: ListingsStateRouteChildren = {
  ListingsStateTypeRoute: ListingsStateTypeRouteWithChildren,
}

const ListingsStateRouteWithChildren = ListingsStateRoute._addFileChildren(
  ListingsStateRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AddressFinderRoute: AddressFinderRoute,
  AddressFinderCartesiaRoute: AddressFinderCartesiaRoute,
  DashboardRoute: DashboardRouteWithChildren,
  HealthRoute: HealthRoute,
  PricingRoute: PricingRoute,
  SignInRoute: SignInRouteWithChildren,
  SignUpRoute: SignUpRouteWithChildren,
  SubscriptionRequiredRoute: SubscriptionRequiredRoute,
  SuccessRoute: SuccessRoute,
  BlogSlugRoute: BlogSlugRoute,
  ListingsStateRoute: ListingsStateRouteWithChildren,
  ListingsCreateRoute: ListingsCreateRoute,
  ListingsMyListingsRoute: ListingsMyListingsRoute,
  AdminIndexRoute: AdminIndexRoute,
  BlogIndexRoute: BlogIndexRoute,
  ListingsIndexRoute: ListingsIndexRoute,
  AdminListingsCreateRoute: AdminListingsCreateRoute,
  ApiAddressDetailsRoute: ApiAddressDetailsRoute,
  ApiAddressSearchRoute: ApiAddressSearchRoute,
  ApiAddressSelectRoute: ApiAddressSelectRoute,
  ApiAddressValidateRoute: ApiAddressValidateRoute,
  AdminListingsIndexRoute: AdminListingsIndexRoute,
  AdminListingsEditIdRoute: AdminListingsEditIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
